apiversion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels: 
    project: roboshop
    component: frontend
    tier: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: frontend
      tier: ui
  template:
    metadata:
      name: frontend
      labels:
        project: roboshop
        component: frontend
        tier: ui
    spec:
      containers:
      - name: frontend
        image: someshwarsangaraju/frontend:v1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: frontend
    tier: ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    